{
 "title": "Kafka Overview",
 "tags": [ "kafka" ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Kafka Brokers Up",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "count(kafka_server_broker_topic_metrics_messages_in_total)",
     "legendFormat": "Brokers"
    }
   ]
  },
  {
   "title": "Messages In / Sec",
   "type": "graph",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(kafka_server_broker_topic_metrics_messages_in_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)"
    }
   ]
  }
 ]
}