# infra/overlays/dev/mailhog/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/mailhog # Reference the generated base manifests
  - 41-mailhog-ui-ingress.yaml

namespace: mailhog # Ensure all resources are in the 'mailhog' namespace
