apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181 # Client port
    name: client
  - port: 2888 # Peer port
    name: peer
  - port: 3888 # Leader election port
    name: leader-election
  clusterIP: None # This makes it a headless service
  selector:
    app: zookeeper