# infra/overlays/dev/opensearch/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/opensearch # Reference the generated base manifests
  - 41-opensearch-dashboards-ingress.yaml

namespace: opensearch # Ensure all resources are in the 'opensearch' namespace
