apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8092 # Service port
      targetPort: 8081 # Container port
      #nodePort: 30000 # A specific port on your node, typically in the 30000-32767 range
  type: LoadBalancer # Expose outside the cluster