apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mongo

resources:
- 01-namespace.yaml
- 02-mongodb-pvc.yaml
#- 03-mongo-secret.yaml
- 21-mongodb-deployment.yaml
- 22-mongodb-service.yaml
- 31-mongo-express-deployment.yaml
- 32-mongo-express-service.yaml

secretGenerator:
  - name: mongo-secret
    envs:
      - .env.secret
generatorOptions:
  disableNameSuffixHash: true

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: mongo-stack

images:
- name: mongo
  newName: mongo
  newTag: 8.0.10
- name: mongo-express
  newName: mongo-express
  newTag: 1.0.2   