apiVersion: v1
kind: Service
metadata:
  name: opensearch-headless
  namespace: opensearch
  labels:
    app: opensearch
spec:
  ports:
  - port: 9200 # HTTP port
    name: http
  - port: 9600 # Transport port (used for node-to-node communication)
    name: transport
  clusterIP: None # This makes it a headless service
  selector:
    app: opensearch