# infra/overlays/dev/mongo/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/mongo # Reference the generated base manifests
  - 41-mongo-express-ingress.yaml

namespace: mongo # Ensure all resources are in the 'mongo' namespace
