# nuxeo/42-nuxeo-worker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxeo-worker-deployment
  labels:
    app: nuxeo-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxeo-worker
  template:
    metadata:
      labels:
        app: nuxeo-worker
    spec:
      terminationGracePeriodSeconds: 120
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["nuxeo-worker"]
              topologyKey: kubernetes.io/hostname
      #serviceAccountName: cluster-wide-reader-sa # Inherits the pull secret  
      #automountServiceAccountToken: true
      imagePullSecrets:
        - name: registry-cred
      containers:
        - name: nuxeo-worker
          image: docker-private.packages.nuxeo.com/nuxeo/nuxeo
          imagePullPolicy: IfNotPresent
          env:
            - name: NUXEO_CLID
              valueFrom:
                secretKeyRef:
                  name: nuxeo-secret
                  key: clid
            - name: NUXEO_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nuxeo-secret
                  key: mongodb-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nuxeo-secret
                  key: mongodb-password 
            - name: NUXEO_S3STORAGE_AWSID
              valueFrom:
                secretKeyRef:
                  name: nuxeo-secret
                  key: aws-accesskey
            - name: NUXEO_S3STORAGE_AWSSECRET
              valueFrom:
                secretKeyRef:
                  name: nuxeo-secret
                  key: aws-secretkey                      
          envFrom:
            - configMapRef:
                name: nuxeo-common-config
            - configMapRef:
                name: nuxeo-worker-config
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          volumeMounts:
            - name: nuxeo-config-00-core
              mountPath: /etc/nuxeo/conf.d/00-core.conf
              subPath: 00-core.conf
            - name: nuxeo-config-00-system
              mountPath: /etc/nuxeo/conf.d/00-system.conf
              subPath: 00-system.conf
            - name: nuxeo-config-log4j2
              mountPath: /opt/nuxeo/server/lib/log4j2.xml
              subPath: log4j2.xml            
            - name: nuxeo-stream
              mountPath: /opt/nuxeo/server/stream
            - name: nuxeo-tmp
              mountPath: /tmp
            - name: nuxeo-logs
              mountPath: /var/log/nuxeo
            - name: gcp-credentials-volume
              mountPath: /opt/nuxeo/gcp-credentials
              readOnly: true
      volumes:
        - name: nuxeo-stream
          emptyDir: {}
        - name: nuxeo-tmp
          emptyDir: {}
        - name: nuxeo-logs
          emptyDir: {}
        - name: nuxeo-config-00-core
          configMap:
            name: nuxeo-config-00-core
        - name: nuxeo-config-00-system
          configMap:
            name: nuxeo-config-00-system
        - name: nuxeo-config-log4j2
          configMap:
            name: nuxeo-config-log4j2             
        - name: gcp-credentials-volume
          secret:
            secretName: gcp-credentials
            items:
            - key: gcp-key
              path: gcp-credentials.json

