apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nuxeo-api-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Adjust size as needed for Nuxeo data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nuxeo-api-stream
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # For Nuxeo stream data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nuxeo-api-import
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # For Nuxeo import directory