apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
  - port: 9092 # Kafka broker port
    name: broker
  clusterIP: None
  selector:
    app: kafka