apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: kafka
spec:
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: 8093 # Service port
      targetPort: 8080 # Container port
      #nodePort: 30001 # Choose an available port in the 30000-32767 range
  type: LoadBalancer # Expose outside the cluster
