apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka

resources:
- 01-namespace.yaml
- 02-kafka-pvc.yaml
- 03-zookeeper-pvc.yaml
- 21-kafka-statefulset.yaml
- 22-kafka-headless-service.yaml
- 31-kafka-ui-deployment.yaml
- 32-kafka-ui-service.yaml
- 41-zookeeper-headless-service.yaml
- 42-zookeeper-statefulset.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: kafka-stack

images:
- name: confluentinc/cp-kafka
  newName: confluentinc/cp-kafka
  newTag: 7.5.0 
- name: provectuslabs/kafka-ui
  newName: provectuslabs/kafka-ui
  newTag: latest   
- name: confluentinc/cp-zookeeper
  newName: confluentinc/cp-zookeeper
  newTag: 7.5.0   
