apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./nuxeo

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: nuxeo-stack
    