apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nuxeo-worker-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Adjust size as needed for Nuxeo data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nuxeo-worker-stream
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # For Nuxeo stream data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nuxeo-worker-import
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # For Nuxeo import directory