apiVersion: v1
kind: ConfigMap
metadata:
  name: nuxeo-api-config
data:
  NUXEO_RUN_MODE: "api"
  NUXEO_DEV: "true"
  NUXEO_SERVER_HTTP_ENABLED: "true"
  NUXEO_SERVER_HTTPS_ENABLED: "true"

  # Participate in stream-based pub-sub
  NUXEO_STREAM_PUBSUB_ENABLED: "true"

  # Participate in Kafka streams even if not processing work
  NUXEO_STREAM_WORK_ENABLED: "true"

  # Enable bulk action submission
  NUXEO_BULK_ACTION_ENABLED: "true"

  # Optional debug
  NUXEO_JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787"
  NUXEO_SELECTION_SELECT_ALL_ENABLED: "true"
