# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mailhog  

resources:
- namespace.yaml
- mailhog-pvc.yaml
- mailserver-deployment.yaml
- mailserver-service.yaml
# You can add common labels or annotations here if needed
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: mailhog-stack

images:
- name: mailhog/mailhog  # This matches whatever image name is in your deployment.yaml
  newName: mailhog/mailhog  # Or your custom registry path
  newTag: latest  # Or a specific version like v1.0.1    
