# my-tekton-project/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all the base resources for your Tekton setup
resources:
  - tasks/git-clone-task.yaml
  - tasks/maven-build-task.yaml
  - tasks/kaniko-task.yaml
  - pipelines/maven-ci-pipeline.yaml
  - resources/service-account.yaml
  - resources/registry-secret.yaml
  # If maven-cache-pvc is a standalone PVC, list it here.
  # If it's a VolumeClaimTemplate within the Pipeline, it's defined there.
  # - resources/maven-cache-pvc.yaml

# Optional: Generate ConfigMaps or Secrets from files or literals for common parameters
# configMapGenerator:
#   - name: pipeline-common-params
#     literals:
#       - DEFAULT_BRANCH=main
#       - DEFAULT_REPO_ORG=my-org

generatorOptions:
  # Disables the hash suffix for generated resource names, useful for predictable names
  disableNameSuffixHash: true