apiVersion: v1
kind: Service
metadata:
  name: minio-service-lb
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
    - name: s3-api
      port: 9000
      targetPort: 9000
    - name: web-ui
      port: 8091
      targetPort: 9001

