apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio

resources:
  - 01-namespace.yaml
  - 02-pvc.yaml
  - 04-deployment.yaml
  - 05-service-clusterip.yaml
  - 06-service-loadbalancer.yaml

secretGenerator:
  - name: minio-secret
    envs:
      - .env.minio.secret
generatorOptions:
  disableNameSuffixHash: true  

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: nuxeo-stack
