apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- elasticsearch/
#- opensearch/
- kafka/
- mongo/
- minio/
- mailhog/
#- monitoring/
- sftp/

images:
- name: docker.elastic.co/elasticsearch/elasticsearch
  newName: docker.elastic.co/elasticsearch/elasticsearch
  newTag: 8.13.0  
- name: docker.elastic.co/kibana/kibana
  newName: docker.elastic.co/kibana/kibana
  newTag: 8.13.0   
- name: confluentinc/cp-kafka
  newName: confluentinc/cp-kafka
  newTag: 7.5.0 
- name: dprovectuslabs/kafka-ui
  newName: dprovectuslabs/kafka-ui
  newTag: latest   
- name: confluentinc/cp-zookeeper
  newName: confluentinc/cp-zookeeper
  newTag: 7.5.0   
- name: mailhog/mailhog
  newName: mailhog/mailhog
  newTag: latest    
- name: mongo
  newName: mongo
  newTag: 8.0.10
- name: mongo-express
  newName: mongo-express
  newTag: 1.0.2    
- name: opensearchproject/opensearch
  newName: opensearchproject/opensearch
  newTag: 2.13.0
- name: opensearchproject/opensearch-dashboards
  newName: opensearchproject/opensearch-dashboards
  newTag: 2.13.0     
- name: quay.io/minio/minio
  newName: quay.io/minio/minio
  newTag: "RELEASE.2025-05-24T17-08-30Z"

patches:
- target:
    kind: Deployment
    name: kibana-deployment
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kibana-deployment
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: kibana
              resources:
                requests:
                  cpu: "500m"
                  memory: "1Gi"
                limits:
                  cpu: "1"
                  memory: "2Gi"