# infra/overlays/dev/kafka/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka # Ensure all resources are in the 'kafka' namespace


resources:
  - ../../../base/kafka # Reference the generated base manifests
  - 41-kafka-ui-ingress.yaml
