apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: maven-kaniko-workflow
spec:
  arguments:
    parameters:
      - name: branch
        value: 2023.27-SNAPSHOT
      - name: repo_org
        value: srasiah
      - name: repo_name
        value: nuxeo-2023
      - name: docker_registry
        value: docker.io/srasiah
      - name: image_name
        value: nuxeo-base
      - name: tag
        value: 2023.27-SNAPSHOT
      - name: mvn_goals
        value: install -Pdistrib -pl docker/nuxeo -am -B -DskipTests -Dnuxeo.skip.enforcer=true -T6 -Xmx4g -Xms2g -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      - name: mvn_props
        value: -Denv=staging -DskipTests=false -Ddocker.base.image=2023.27-SNAPSHOT -Ddocker.platforms=linux/amd64

