# my-tekton-project/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Point to the base directory where the core Tekton resources are defined
bases:
  - ../../base

# Add environment-specific resources, such as a PipelineRun
resources:
  - pipelinerun.yaml # This file will define how you run the pipeline in dev

# Apply patches to modify resources from the base
patches:
  - target:
      kind: Pipeline
      name: maven-ci-pipeline # Reference the base pipeline name
    patch: |-
      # Example: You might patch the pipeline here if you have dev-specific tasks or parameters
      # - op: replace
      #   path: /spec/params/0/default
      #   value: "dev-branch"
  - target:
      kind: Secret
      name: registry-secret # Reference the base secret name
    patch: |-
      # Example: If your dev registry credentials are different, you could patch the secret data here
      # However, for sensitive data, managing separate secrets directly is often safer than patching.
      # - op: replace
      #   path: /data/.dockerconfigjson
      #   value: "your_dev_base64_encoded_docker_config"

# Name prefixes or suffixes for resources in this overlay
nameSuffix: -dev # Adds -dev to all resource names generated by this overlay (e.g., maven-ci-pipeline-dev)

# Optional: Generate environment-specific ConfigMaps
# configMapGenerator:
#   - name: pipeline-dev-params
#     literals:
#       - DOCKER_REGISTRY=dev.docker.io/myregistry