grafana:
  adminPassword: admin

  service:
    type: LoadBalancer
    ports:
      - port: 80
        targetPort: 3000
        protocol: TCP

  persistence:
    enabled: true
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    size: 1Gi

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: 'Provisioned'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards

  extraConfigmapMounts:
    - name: grafana-dashboards
      mountPath: /var/lib/grafana/dashboards
      configMap: grafana-dashboards
      readOnly: true
      defaultMode: 0444

prometheus:
  prometheusSpec:
    retention: 15d
    retentionSize: 10GB
    serviceMonitorSelectorNilUsesHelmValues: true  # <-- fix is here!
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi


  additionalPrometheusRulesMap:
    example-rule:
      groups:
        - name: node.rules
          rules:
            - record: instance:node_cpu:rate5m
              expr: rate(node_cpu_seconds_total[5m])
              labels:
                severity: critical
